prometheus:
  prometheusSpec:
    retention: 15d  # 15일간 데이터 보관
    resources:
      requests:
        cpu: 200m
        memory: 1Gi
      limits:
        cpu: 500m
        memory: 2Gi

alertmanager:
  enabled: true
  
grafana:
  adminPassword: "admin123"  # Grafana 관리자 비밀번호 설정
  service:
    type: ClusterIP
  persistence:
    enabled: true
    size: 10Gi
  dashboardProviders:
    dashboardproviders.yaml:
      apiVersion: 1
      providers:
      - name: 'default'
        orgId: 1
        folder: ''
        type: file
        disableDeletion: false
        editable: true
        options:
          path: /var/lib/grafana/dashboards/default
